### ISSUE TITLE
Feature Request: Make 1st Admin to join the mission a commander by default without needing to vote

### ISSUE THREAD

**Issue by bdux** [Kexanone/COE2_AR#10]
As the description says, 
I think it would be nice to have a joining admin being the commander by default and be able to set the mission parameters.

**Comment by Kexanone** [comment]
This should already be the case. Log in as admin should grant you commander role automatically.

**Comment by 0xmex** [comment]
Can confirm. When I log into as admin, I am automatically becoming the commander as well.

**Comment by bdux** [comment]
It indeed does. Cheers!

**Comment by airtonix** [comment]
If you start this in Local mode this doesn't happen
