### ISSUE TITLE
RHS and Vanilla Factions are mixed up when setting up on dedicated server

### ISSUE THREAD

**Issue by bdux** [Kexanone/COE2_AR#12]
I run COE2 with RHS on Chernarus, and upon logging in and selecting the factions in the scenario settings, I need to choose US Army (Vanilla) to actually get the USAF Faction as playable. If I choose USAF, the playable faction will be set to US Army (Vanilla). 
When I choose MSV as opposing faction, there will be a mix of vanilla and MSV Russians running around in the AOs.

**Comment by Kexanone** [comment]
Yes, US and USAF sometimes get mixed up for some reason. It's a known bug.

> there will be a mix of vanilla and MSV Russians

This isn't actually true. Some RHS MSV troops have older gear like the soviet helmet.

**Comment by Kexanone** [comment]
Looks like a RHS bug. Might also happen in GM, but I resolved it for COE2 in the RHS Patch at least.
