### ISSUE TITLE
Cant set an Insertion point

### ISSUE THREAD

**Issue by Thedabking710** [Kexanone/COE2_AR#17]
Cant set insertion points looked through key binds and everything mods unplayable

**Comment by Kexanone** [comment]
Everything, but a certain window that pops up when you spawn^^

**Comment by Kexanone** [comment]
There's an entry in the map commanding menu for placing an insertion.
![](https://raw.githubusercontent.com/Kexanone/COE2_AR/refs/heads/main/addons/COE2/UI/Textures/FieldManual/MPModes/COE2/Images/InsertionPointCommand.png)

**Comment by Thedabking710** [comment]
For me that menu won’t show up I get the circle to show up but I don’t have any options to place anything I just get the option to place a map marker and the rest are blank will add screen shot shortly. Do I have to set up my key binds to get the map command menu to pop up?

**Comment by Thedabking710** [comment]
![IMG_8431](https://github.com/user-attachments/assets/31f4d5f2-03c5-473b-aafb-8b74b5d286a1)
![IMG_8430](https://github.com/user-attachments/assets/27cf65fb-8271-4edb-b03f-bf22f9c5a779)
![IMG_8429](https://github.com/user-attachments/assets/fa0ed3bd-655a-4a48-a32d-ddaf636990af)

**Comment by Thedabking710** [comment]
Am I doing something wrong?

**Comment by Kexanone** [comment]
Click on this one:
![tmp](https://github.com/user-attachments/assets/9c29f269-987d-4cc1-a585-9baa8a7f3fdf)

**Comment by Thedabking710** [comment]
I figured it out thank you I was trying to place an insertion before generating the AO and would just get the commanding screen after generating the AO the insertion menu popped up for me. Thank you so much!
