### ISSUE TITLE
Respawn on deployed radios

### ISSUE THREAD

**Issue by Mimi-Sa** [Kexanone/COE2_AR#2]
Hi! Thank You for creating COE2. ~~I've already have had good time with it. I noticed, however, that "Destroy Installation"-task does not work (CreateAO does not create this task).~~ In addition, spawning on a deployed radio did not work (spawning on the radio-operator worked just fine). Tried to drop radio-backpack on the ground and deploy it. When trying to deploy it, not such an option was available, only two other, which resulted in just picking up the radio.

**Comment by Kexanone** [comment]
These are two completely separate issues. I edited this ticket to be for the deployed radios, which is indeed a bug. As for destroy installation, they do work if you select a location that has a flat enough area to support them like at the bottom of the main valley in Kunar Province.

**Comment by Mimi-Sa** [comment]
Super! Thank You a lot for clarifying the ”destroy the installation issue. I really appreciate Your fast reply.

Yours,
Mimi-Sa


Kex ***@***.***> kirjoitti 3.7.2024 kello 17.42:

﻿

These are two completely separate issues. I edited this ticket to be for the deployed radios, which is indeed a bug. As for destroy installation, they do work if you select a location that has a flat enough area to support them like at the bottom of the main valley in Kunar Province.

**Comment by Kexanone** [comment]
I was unable to reproduce the issue with deployed radios. I can spawn on them as long as I'm in the same group as the player the placed it.

**Comment by Mimi-Sa** [comment]
I tried to deploy backback-radio for respawn. The radio was the defaut US-one. I got only the option ”Equip” and ”Pick up”. The server was your winter-Everon.
