### ISSUE TITLE
Bug report: Game master mode faction select not working when COE2 is loaded

### ISSUE THREAD

**Issue by Your401kPlan** [Kexanone/COE2_AR#3]
After some rigorous testing I found that when COE2 is loaded on a dedicated server, it prevents factions from being selected as playable or non-playable when the server has switched scenarios to a gamemaster mode. Disabling COE2 re-enables faction selection in game master modes. I can provide any additional info/logs needed.

**Comment by Kexanone** [comment]
COE2 currently overrides the faction selection editor attribute, but it should probably provide it's own attribute in future instead.

**Comment by Kexanone** [comment]
Fixed in adf2317
