### ISSUE TITLE
missions

### ISSUE THREAD

**Issue by markammo57** [Kexanone/COE2_AR#6]
when i create a mission I'm not getting objectives for hvt or kill targets, don't know if you have a fix for this or if its only certain spots on the map. if this is in the works ignore my issue.

**Comment by Kexanone** [comment]
With certain spots on maps, you probably mean the southern region of Kunar Province. HVT and intel objectives will only be generated if compatible buildings are available or if there are sufficiently flat areas for spawning tents.

**Comment by markammo57** [comment]
i'm playing it on everon but i see what you mean, my server is named The Boys if you want to test it for yourself.

**Comment by Kexanone** [comment]
Most locations on Everon should be compatible, except a very few like the southern harbor of Equiry. Posting a screenshot of the locations you think should work, but don't would help.
