### ISSUE TITLE
AI does not move after being engaged

### ISSUE THREAD

**Issue by bdux** [Kexanone/COE2_AR#7]
Playing COE2 with RHS on Chernarus with a bunch of friends, and we noticed that the AI Units fight back, but do not in any way move around. All AI units remain static, be they under fire or not.

**Comment by 0xmex** [comment]
Have you increased the difficulty? What is your server fps, when the ai should get active? Have you set max fps startup parameter attribute? If so, on what value?

**Comment by Kexanone** [comment]
I think the navigation mesh might be broken on Chernarus.

**Comment by bdux** [comment]
Awesome, thank you. Was about to put the Mission config here. Will check later and see if it works.
