### ISSUE TITLE
Change default parameters in mission header

### ISSUE THREAD

**Issue by 0xmex** [Kexanone/COE2_AR#8]
I, as a public server admin, would like to have a setting to have the mission run in automated mode. 
I start up the mission and either a predetermined position gets a unit spawner and/or the AO/mission selection gets automated by a predetermined setting. 

For example I start up the mission, go to a scenario config screen (alongside the difficulty settings and so on) and set a variable to either auto deploy or auto ao mode and restart the mission. The respective setting gets then set automatically.

**Comment by Kexanone** [comment]
Seems a bit ironic, since one of the main goals of version 2 was to go from automatic generation to allowing players to select what they want to play.

**Comment by Kexanone** [comment]
Is this really about automated mode or rather about that the selection process isn't streamlined enough for inexperience players?

**Comment by 0xmex** [comment]
That I didn't knew that the first version was auodeployable. 
Would it be possible to have an own automatic version available? Or set it via a server setting? 

I want to restart the server every 6 hours. As well as when a new Reforger version is being deployed. When this happens I don't want to log onto the server, set the factions and put down a respawn point manually. The mission selection/setup can be done by players (obtainable Commander role?). Or having the option that this is being set within predefined settings (AO size, minimum AI, etc).

**Comment by Kexanone** [comment]
> The mission selection/setup can be done by players (obtainable Commander role?)

The point is that everything can be done with the votable commander role. There's is no need for an admin to select the faction, etc. Think of this game mode more like Game Master (with the votable commander having a similar role). You wouldn't set up a scenario in advance either as admin.

**Comment by 0xmex** [comment]
Now I've understand it. I thought an admin needs to set those parameters AND a spawn point ... 
Would there be a way to autoset my desired factions via missionHeader parameters?

**Comment by Kexanone** [comment]
Yes, being able to change the default parameters in the mission header would be good. I'll changed the title accordingly.
