### ISSUE TITLE
Feature Request: Raise the player count

### ISSUE THREAD

**Issue by 0xmex** [Kexanone/COE2_AR#9]
I, as a public server admin, would like to have more players on the server. Could the player count for the mission instead been tied to the player cap on the server? For example allowing 128 players mission side, but then set it to 48 on the server config? 
There is the cap increase mod on the workshop (https://reforger.armaplatform.com/workshop/6214331D54B3ECDE-HIgherplayercountforCOE2), but 32 might not be enough (one day).

Or is this something I need to create my own mod/scenario from your source to adjust this to my needs?

**Comment by Kexanone** [comment]
I thought the count you specify in the server config already overrides the count of the mission. If it in fact doesn't, you could try to check what happens if you add `"m_iPlayerCount": 32` in the `missionHeader` section of the the server config in addition.

**Comment by 0xmex** [comment]
Good to know, will test it out and come back to you with my findings.

**Comment by 0xmex** [comment]
Can confirm it working. Can raise to 32, but not above. Changed
```
                "m_iPlayerCount": 32
             [...]
        "maxPlayers": 32,
```


I guess this is the natural limit of the server? Would need to find a way to increase this limit, but this isn't related to the mission I pressume ...
Closing the issue/feature request.

**Comment by Kexanone** [comment]
You have to change both `m_iPlayerCount` and `maxPlayers` to your desired value. `32` was just an example ;)

**Comment by Kartoffelkee** [comment]
is the mission header located inside the server json confic file?

**Comment by 0xmex** [comment]
@Kartoffelkee Yes it is! Including ACE Medical config it looks like this for me: 

```
            "missionHeader": {
                "m_ACE_Settings": {
                    "m_ACE_Medical_Settings": {
                        "m_bHealSupplyUsageEnabled": 0,
                        "m_bSecondChanceOnHeadEnabled": 1,
                        "m_fMedicalKitMaxHealScaled": 1,
                        "m_fSecondChanceRegenScale": 0.025
                    }
                },
                "m_iPlayerCount": 48
            },
```
